const mainHead=document.getElementById("main-heading");
mainHead.innerHTML="Fruit World";
mainHead.style.color="orange";
const header=document.getElementById('header');
header.style.backgroundColor="green";
header.style.borderBottom="solid orange";
const fruits=document.getElementById("basket-heading");
fruits.style.color="green";
const thanks=document.getElementById("thanks");
thanks.innerHTML="<p>Please visit us again</p>"